"""Analytic synthetic scene generation for image-method validation."""

from synthworkshop.cross_sections import (
    CircularCrossSection,
    CrossSection,
    CrossSectionEvaluation,
    EllipticCrossSection,
    RibbonCrossSection,
    RotatingEllipticCrossSection,
    SuperellipseCrossSection,
    VariableCircularCrossSection,
    VariableEllipticCrossSection,
)
from synthworkshop.grid import GridSpec
from synthworkshop.ground_truth import SceneTruth
from synthworkshop.io import SceneExportManifest, export_scene, safe_name
from synthworkshop.plotting import (
    choose_projection_axis,
    plot_3d_skeletons,
    plot_orthogonal_slices,
    plot_projection,
    project_image,
    scene_legend_table,
    write_scene_gallery,
)
from synthworkshop.primitives import (
    Centreline,
    ConeObject,
    EllipsoidObject,
    FrustumObject,
    LineCurve,
    PolylineCurve,
    ReferenceFrame,
    SinusoidalCurve,
    SlabObject,
    SphereObject,
    TubeObject,
    build_reference_guided_frame,
)
from synthworkshop.profiles import (
    AsymmetricLinearProfile,
    ConstantProfile,
    EdgeEnhancedProfile,
    GaussianRadialProfile,
    HollowCoreProfile,
    LinearRadialProfile,
    LongitudinalGradientProfile,
    MultiPeakRadialProfile,
    OneSidedLesionProfile,
    PeriodicLongitudinalProfile,
    RadialLongitudinalGradientProfile,
    ScalarProfile,
    ScalarProfileEvaluation,
    SigmoidBoundaryProfile,
)
from synthworkshop.scenes import (
    CompositionRules,
    LabelMode,
    MaskRules,
    ObjectRole,
    OverlapPolicy,
    OverlapReport,
    RenderableObject,
    RenderedScene,
    ScalarBlend,
    SceneObjectMetadata,
    compose_rendered_scenes,
    render_objects,
)
from synthworkshop.scenes.config import (
    SceneObjectSpec,
    SceneSpec,
    load_scene_spec,
    render_scene_from_dict,
    render_scene_from_path,
    render_scene_from_spec,
    scene_spec_from_dict,
    scene_spec_to_dict,
)
from synthworkshop.topology import (
    GraphCentrelineSet,
    GraphEdge,
    GraphNode,
    GraphSpec,
    GraphTubeObject,
    graph_edge_curve,
    graph_spec_from_dict,
    sample_graph_edges,
)

version = "0.1.0"
__version__ = version

__all__ = [
    "AsymmetricLinearProfile",
    "Centreline",
    "CircularCrossSection",
    "CompositionRules",
    "ConeObject",
    "ConstantProfile",
    "CrossSection",
    "CrossSectionEvaluation",
    "EdgeEnhancedProfile",
    "EllipsoidObject",
    "EllipticCrossSection",
    "FrustumObject",
    "GaussianRadialProfile",
    "GraphCentrelineSet",
    "GraphEdge",
    "GraphNode",
    "GraphSpec",
    "GraphTubeObject",
    "GridSpec",
    "HollowCoreProfile",
    "LabelMode",
    "LineCurve",
    "LinearRadialProfile",
    "LongitudinalGradientProfile",
    "MaskRules",
    "MultiPeakRadialProfile",
    "ObjectRole",
    "OneSidedLesionProfile",
    "OverlapPolicy",
    "OverlapReport",
    "PeriodicLongitudinalProfile",
    "PolylineCurve",
    "RadialLongitudinalGradientProfile",
    "ReferenceFrame",
    "RenderableObject",
    "RenderedScene",
    "RibbonCrossSection",
    "RotatingEllipticCrossSection",
    "ScalarBlend",
    "ScalarProfile",
    "ScalarProfileEvaluation",
    "SceneExportManifest",
    "SceneObjectMetadata",
    "SceneObjectSpec",
    "SceneSpec",
    "SceneTruth",
    "SigmoidBoundaryProfile",
    "SinusoidalCurve",
    "SlabObject",
    "SphereObject",
    "SuperellipseCrossSection",
    "TubeObject",
    "VariableCircularCrossSection",
    "VariableEllipticCrossSection",
    "__version__",
    "build_reference_guided_frame",
    "choose_projection_axis",
    "compose_rendered_scenes",
    "export_scene",
    "graph_edge_curve",
    "graph_spec_from_dict",
    "load_scene_spec",
    "plot_3d_skeletons",
    "plot_orthogonal_slices",
    "plot_projection",
    "project_image",
    "render_objects",
    "render_scene_from_dict",
    "render_scene_from_path",
    "render_scene_from_spec",
    "safe_name",
    "sample_graph_edges",
    "scene_legend_table",
    "scene_spec_from_dict",
    "scene_spec_to_dict",
    "version",
    "write_scene_gallery",
]
